[package]
name = "shared_secret_creator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
x25519-dalek = "1.2.0"
blake2 = "0.9"
rand = "0.7"
